# Generated by Django 6.0.2 on 2026-03-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord_tbl',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resourceType', models.CharField(default='', max_length=500)),
                ('resourceId', models.CharField(default='', max_length=500)),
                ('name', models.JSONField()),
                ('gender', models.CharField(default='', max_length=100)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('identifier', models.JSONField()),
                ('telecom', models.JSONField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
