# Generated by Django 6.0.2 on 2026-03-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patientrecord_tbl_resourceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord_tbl',
            name='passportNumber',
            field=models.CharField(default='Nil', max_length=500),
        ),
    ]
