# Generated by Django 6.0.2 on 2026-03-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patientrecord_tbl_passportnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
