# Generated by Django 6.0.2 on 2026-03-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sessionaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionaccesslog',
            name='action',
            field=models.CharField(default='Nil', max_length=100),
        ),
    ]
