# Generated by Django 6.0.2 on 2026-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sessionaccesslog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord_tbl',
            name='passportNumber',
            field=models.CharField(db_column='passportNumber', max_length=500),
        ),
    ]
