# Generated by Django 6.0.2 on 2026-03-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_patientrecord_tbl_passportnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord_tbl',
            name='passportNumber',
            field=models.CharField(max_length=500),
        ),
    ]
