# Generated by Django 6.0.2 on 2026-03-01 07:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_patientrecord_tbl_passportnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord_tbl',
            name='resourceId',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=500, unique=True),
        ),
    ]
