# Generated by Django 6.0.2 on 2026-03-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_patientrecord_tbl_resourceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord_tbl',
            name='resourceId',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
